resources:
  pipelines:
  - pipeline: akskubernetesbuild
    source: 'aks-kubernetes-build'
    trigger: true

trigger:
- none

# Variables
variables:
  tag: '$(resources.pipeline.akskubernetesbuild.runID)'

stages:
- stage: Deploy_Dev
  displayName: Deploy Dev stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'aksdemo-dev-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Tag used = $(tag)"
            displayName: "Print Tag"

          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretType: 'dockerRegistry'
              secretName: 'ACRImagePullSecret'
              dockerRegistryEndpoint: 'acrforaksdemo1-sc'
              
          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: $(Pipeline.Workspace)/kube-manifests/01-Deployment-and-LoadBalancer-Service.yml
              imagePullSecrets: |
                $(ACRImagePullSecret)
              containers: |
                acrforaksdemo1.azurecr.io/custom2aksnginxapp1:$(tag)